# ---------------
# --- NETWORK ---
# ---------------
networks:
  hexagon-network:
    driver: bridge

# ---------------
# --- VOLUMES ---
# ---------------
volumes:
  hexagon_db_data:

# ----------------
# --- SERVICES ---
# ----------------
services:
  # ----------------
  # --- POSTGRES ---
  # ----------------
  hexagon_db:
    image: postgres:latest
    container_name: hexagon_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hexagon_db
    volumes:
      - hexagon_db_data:/var/lib/postgresql
    networks:
      - hexagon-network
    ports:
      - "5432:5432"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # ---------------
  # --- HEXAGON ---
  # ---------------
  hexagon_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hexagon_app
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: hexagon_db
      POSTGRES_DATABASE: hexagon_db
    ports:
      - "8080:8080"
    depends_on:
      - hexagon_db
    networks:
      - hexagon-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"